<?php

namespace Database\Seeders;

use App\Models\User;
use App\Mail\UpdateProfileMail;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            // ['name' => 'Admin', 'email' => 'fyndconcepts@gmail.com'],
            // ['name' => 'Ezekiel Afolabi', 'email' => 'ezekielafolabi22@gmail.com']
            // ['name' => 'Nandom Kuchi', 'email' => 'nandomkumchi01@gmail.com'],
            ['name' => 'Simi Oke', 'email' => 'similolu03@gmail.com']
        ];

        // $users = array(
        //     array('user_email' => 'admin@fyndconcepts.org','display_name' => 'Admin'),
        //     array('user_email' => 'adebayorakindele@gmail.com','display_name' => 'BaroTech'),
        //     array('user_email' => 'tanimowoadedayo@gmail.com','display_name' => 'tanimowo adedayo'),
        //     array('user_email' => 'oluwaseunelijah1010@gmail.com','display_name' => 'Elijah Oluwaseun'),
        //     array('user_email' => 'elitetechhub10@gmail.com','display_name' => 'Elite World Communications'),
        //     array('user_email' => 'richdad4real@yahoo.com','display_name' => 'Richard'),
        //     array('user_email' => 'okoroji03@gmail.com','display_name' => 'ANGELA OKOROJI (BOSSANGIE)'),
        //     array('user_email' => 'samodunayo@gmail.com','display_name' => 'Samodunayo'),
        //     array('user_email' => 'owoheyefehmi@gmail.com','display_name' => 'Fem~lad Global Resources and Solar &amp; Electrical technicians'),
        //     array('user_email' => 'steven.adeyinka@gmail.com','display_name' => 'Stephen Adeyinka'),
        //     array('user_email' => 'Segeken@gmail.com','display_name' => 'Segeken'),
        //     array('user_email' => 'richarddada35@gmail.com','display_name' => 'Richard Dada'),
        //     array('user_email' => 'oladejisobowale@gmail.com','display_name' => 'Oladeji Sobowale'),
        //     array('user_email' => 'fyndconcepts@gmail.com','display_name' => 'Fynd Concepts'),
        //     array('user_email' => 'shobolaabayomi@gmail.com','display_name' => 'shobola abayomi'),
        //     array('user_email' => 'reubenadesola06@gmail.com','display_name' => 'Reuben'),
        //     array('user_email' => 'amosoluwayemisi257@gmail.com','display_name' => 'brightandbeautifulmakeover'),
        //     array('user_email' => 'yenboravisluettah@gmail.com','display_name' => 'bimak73555'),
        //     array('user_email' => 'kamilkavu@branchom.com','display_name' => 'bees'),
        //     array('user_email' => 'oladosukhehinde@gmail.com','display_name' => 'Kennivogue'),
        //     array('user_email' => 'rafdaniel30@gmail.com','display_name' => 'Florence Rotibi'),
        //     array('user_email' => 'bosede_florence@yahoo.com','display_name' => 'Rafdaniel'),
        //     array('user_email' => 'angelaokoroji03@gmail.com','display_name' => 'angiieeoo'),
        //     array('user_email' => 'test@testtt.ttt','display_name' => 'test@testtt.ttt'),
        //     array('user_email' => 'ibiyemialabi@gmail.com','display_name' => 'Ms__queenteee44ver2'),
        //     array('user_email' => 'bayodekolawole30@gmail.com','display_name' => 'Kolawole Bayode'),
        //     array('user_email' => 'abdulsegun1986@gmail.com','display_name' => 'Musa'),
        //     array('user_email' => 'everymarch23@yahoo.com','display_name' => 'ifeoluwa'),
        //     array('user_email' => 'sinasamsonsina@gmail.com','display_name' => 'Omoba Sina'),
        //     array('user_email' => 'samuelchikodili567@gmail.com','display_name' => 'Samm7'),
        //     array('user_email' => 'Omoba247@gmail.com','display_name' => 'Omobagas247'),
        //     array('user_email' => 'lummystitches@gmail.com','display_name' => 'Lummy Stitches'),
        //     array('user_email' => 'ajayi.ayodejicharis@gmail.com','display_name' => 'Timini'),
        //     array('user_email' => 'Sinagasfiller247@gmail.com','display_name' => 'Sina Gas 247'),
        //     array('user_email' => 'osenieniola572@gmail.com','display_name' => 'Eniola oseni'),
        //     array('user_email' => 'theboyscollections10@gmail.com','display_name' => 'The Boys Collections'),
        //     array('user_email' => 'Ebonystitches20@gmail.com','display_name' => 'Ebonystitches'),
        //     array('user_email' => 'tpompaydont4k@gmail.com','display_name' => 'Jasmadels'),
        //     array('user_email' => 'classictech18@gmail.com','display_name' => 'De classictech'),
        //     array('user_email' => 'Idowuayodejiseun@gmail.com','display_name' => 'Arise and shine Systems Services'),
        //     array('user_email' => 'aladesuyiabimbola01@gmail.com','display_name' => 'Aladesuyi Abimbola'),
        //     array('user_email' => 'djspinny35@gmail.con','display_name' => 'djspinny35'),
        //     array('user_email' => 'chenemetsynergyglobal@gmail.com','display_name' => 'CHEN-EMET SYNERGY GLOBAL'),
        //     array('user_email' => 'adedeji_adewale@yahoo.com','display_name' => 'waledej'),
        //     array('user_email' => 'Okonkwo444@gmail.com','display_name' => 'Akp2ventures'),
        //     array('user_email' => 'padetony4real@yahoo.com','display_name' => 'Bienaimee Decor'),
        //     array('user_email' => 'oladimejiosobu18@gmail.com','display_name' => 'Dimmy55'),
        //     array('user_email' => 'omolara.olagookun@gmail.com','display_name' => 'Mimiola'),
        //     array('user_email' => 'Okodo2020@gmail.com','display_name' => 'EVEGREAT'),
        //     array('user_email' => 'ezekialafolabi11@gmail.com','display_name' => 'olivergbenga'),
        //     array('user_email' => 'bellokazeemjames18@gmail.com','display_name' => 'Grace Comms'),
        //     array('user_email' => 'odewolelawrence18@gmail.com','display_name' => 'Mr Tee'),
        //     array('user_email' => 'ayodelesamson3176@gmail.com','display_name' => 'Olabisi02'),
        //     array('user_email' => 'fatimaughulu232@gmail.com','display_name' => 'Angel Bae'),
        //     array('user_email' => 'angelughulu@gmail.com','display_name' => 'Ughulu Fatima'),
        //     array('user_email' => 'Philchi75@gmail.com','display_name' => 'Philchilly'),
        //     array('user_email' => 'chibuzor_philip@yahoo.com','display_name' => 'Phil signature'),
        //     array('user_email' => 'sulymanhameedah18@gmail.com','display_name' => 'Oyin empire'),
        //     array('user_email' => 'tosinmercy16@gmail.com','display_name' => 'Tosin Mercy'),
        //     array('user_email' => 'mosesobey44@gmail.com','display_name' => 'Engr Obey'),
        //     array('user_email' => 'omonirasolomon72@gmail.com','display_name' => 'Little Solo'),
        //     array('user_email' => 'meeknessoluwatosin@gmail.com','display_name' => 'oluwatosin meekness'),
        //     array('user_email' => 'deleleke2002@gmail.com','display_name' => 'Adeleke Kehinde'),
        //     array('user_email' => 'aondowasetsuaa@gmail.com','display_name' => 'ATSON FURNITURE'),
        //     array('user_email' => 'tannyeadi@gmail.com','display_name' => 'Tanny_ea Digital print'),
        //     array('user_email' => 'wisechoiz@gmail.com','display_name' => 'WISECHOIZ'),
        //     array('user_email' => 'archangeljizee@gmail.com','display_name' => 'Tech3nity'),
        //     array('user_email' => 'rotimioladedunye@gmail.com','display_name' => 'Ejanla01'),
        //     array('user_email' => 'Kareejoshua@gmail.com','display_name' => 'KAREEM'),
        //     array('user_email' => 'Olaniranolabode75@gmail.com','display_name' => 'Olaniran olabode'),
        //     array('user_email' => 'olaniyannansiruolanrewaju@gmail.com','display_name' => 'OLANIYAN NANSIRU'),
        //     array('user_email' => 'giamicheals1313@gmail.com','display_name' => 'Omogbolahan'),
        //     array('user_email' => 'hacklam18@gmail.com','display_name' => 'sailsakeem'),
        //     array('user_email' => 'theeventsetup@gmail.com','display_name' => 'KRATIVE'),
        //     array('user_email' => 'joshuabiola84@gmail.com','display_name' => 'JOSHUA DIGITAK'),
        //     array('user_email' => 'damilolaabigaildurojaye@gmail.com','display_name' => 'DAMLAD16'),
        //     array('user_email' => 'madereadyinteriors@gmail.com','display_name' => '@MADEREADY'),
        //     array('user_email' => 'Prinfod1@gmail.com','display_name' => 'Prinfod'),
        //     array('user_email' => 'acircle000@gmail.com','display_name' => 'CYPHER MOORE'),
        //     array('user_email' => 'biodunbankole34@gmail.com','display_name' => 'ABIODUN100'),
        //     array('user_email' => 'Oduscouture@gmail.com','display_name' => 'Odus'),
        //     array('user_email' => 'Itunufatimehin@gmail.com','display_name' => 'Styledbyitunu'),
        //     array('user_email' => 'shawierichie@gmail.com','display_name' => 'Shawie'),
        //     array('user_email' => 'emmamag231@gmail.com','display_name' => 'Toyin fab'),
        //     array('user_email' => 'Lawalhabeeb944@gmail.com','display_name' => 'Habeeb100'),
        //     array('user_email' => 'ADEGBOROQUDUS111@GMAIL.COM','display_name' => 'QUDUS ADEGBORO'),
        //     array('user_email' => 'oladapoabdulgafarlekan@gmail.com','display_name' => 'OLAMILEKAN100'),
        //     array('user_email' => 'Tomiwaokunola@gmail.com','display_name' => 'Adetomsss'),
        //     array('user_email' => 'olorunjedanofiu@gmail.com','display_name' => 'OLORUNJEDA100'),
        //     array('user_email' => 'adeoluodusanya13@gmail.com','display_name' => 'ADEOLU100'),
        //     array('user_email' => 'owolabimuidin@gmail.com','display_name' => 'OWOLABI100'),
        //     array('user_email' => 'taiwoemmy21@gmail.com','display_name' => 'TAIWO100'),
        //     array('user_email' => 'ogunyemiomotola06@gmail.com','display_name' => 'OGUNYEMI100'),
        //     array('user_email' => 'osilaja@gmail.com','display_name' => 'OSILAJA100'),
        //     array('user_email' => 'fridayataigbe6@gmail.com','display_name' => 'FRADAY100'),
        //     array('user_email' => 'hinfotechnology25@gmail.com','display_name' => 'Hinfo Technology'),
        //     array('user_email' => 'Olaitandamilola737@gmail.com','display_name' => 'DAMILOLA100'),
        //     array('user_email' => 'okeoluwabukolamary@gmail.com','display_name' => 'B\'s Beddings'),
        //     array('user_email' => 'Olagunroyeolamigbowomichael@gmail.com','display_name' => 'MCartoon'),
        //     array('user_email' => 'marianwaltermarianwalter@gmail.com','display_name' => 'HARIDUNNU100'),
        //     array('user_email' => 'adwarado2021@gmail.com','display_name' => 'Rado9ice Decor'),
        //     array('user_email' => 'h.ssodiqadeyemi@gmail.com','display_name' => 'Hardey'),
        //     array('user_email' => 'ayobamiabayomi2208@gmail.com','display_name' => 'Ayobami100'),
        //     array('user_email' => 'more2classic015@gmail.com','display_name' => 'ABDULAZEEZ100'),
        //     array('user_email' => 'babawalekabirat4@gmail.com','display_name' => 'Babawale'),
        //     array('user_email' => 'iwupromise0009@gmail.com','display_name' => 'Iwu promise'),
        //     array('user_email' => 'adjevin360@gmail.com','display_name' => 'DUPSON100'),
        //     array('user_email' => 'Yusufrasak109@gmail.com','display_name' => 'Abanishe Ray'),
        //     array('user_email' => 'Ayankeyemd@gmail.com','display_name' => 'Kelly8921'),
        //     array('user_email' => 'ayinteriorfurniture@gmail.com','display_name' => 'IBRAHIM100'),
        //     array('user_email' => 'christekpen21@gmail.com','display_name' => 'CHRISTOPHER100'),
        //     array('user_email' => 'Olayemihassan21@gmail.com','display_name' => 'ISMAIL100'),
        //     array('user_email' => 'Damidiva.Catering@gmail.com','display_name' => 'OLUWATOSIN100'),
        //     array('user_email' => 'giftedonyiiu@gmail.com','display_name' => 'Onyinye'),
        //     array('user_email' => 'arowosegbeoluwaloyemisi@gmail.com','display_name' => 'OLUWALOYEMISI'),
        //     array('user_email' => 'samuelajiya56@gmail.com','display_name' => 'Stsams'),
        //     array('user_email' => 'paulpwasposam@gmail.com','display_name' => 'Chon-Kiss Choice'),
        //     array('user_email' => 'emdeeclassic@gmail.com','display_name' => 'Emdeeclassic'),
        //     array('user_email' => 'jamesshedrackyinta@gmail.com','display_name' => 'Milan Footwear'),
        //     array('user_email' => 'disephogini08@gmail.com','display_name' => 'miss2mrs bouquets'),
        //     array('user_email' => 'ugwujoshua071@gmail.com','display_name' => 'ugwu Joshua Onyedikachi'),
        //     array('user_email' => 'suzanegboja88@gmail.com','display_name' => 'L.Brown'),
        //     array('user_email' => 'Poab007@gmail.com','display_name' => 'AKINOLA100'),
        //     array('user_email' => 'Oyedeleesther27@gmail.com','display_name' => 'OYEDELE100'),
        //     array('user_email' => 'amoleidowu2000@gmail.com','display_name' => 'AMOLE100'),
        //     array('user_email' => 'emmyatlove@gmail.com','display_name' => 'Egoism'),
        //     array('user_email' => 'olufemiemmanul1991@gmail.com','display_name' => 'olufemi'),
        //     array('user_email' => 'samstarfooties@gmail.com','display_name' => 'SOBOWALE100'),
        //     array('user_email' => 'jamesmark08963@gmail.com','display_name' => 'Jamesmark'),
        //     array('user_email' => 'ayodavid.ajayi@gmail.com','display_name' => 'Ayo David'),
        //     array('user_email' => 'Peterakande4545@gmail.com','display_name' => 'Psmart'),
        //     array('user_email' => 'georgeelueze@gmail.com','display_name' => 'George'),
        //     array('user_email' => 'nidettocasual@gmail.com','display_name' => 'Nidetto Casual'),
        //     array('user_email' => 'Urubejairus7@gmail.com','display_name' => 'Jesterlight Barbing salon'),
        //     array('user_email' => 'babybliss117@gmail.com','display_name' => 'Alashe Morenikeji'),
        //     array('user_email' => 'olufemiemmanuel1991@gmail.com','display_name' => 'Olufemi Emmanuel'),
        //     array('user_email' => 'taoreedquadri325@gmail.com','display_name' => 'Ayomide'),
        //     array('user_email' => 'Bishopmaduka6@gmail.com','display_name' => 'Blessing'),
        //     array('user_email' => 'ogabishop82@gmail.co','display_name' => 'Bishop'),
        //     array('user_email' => 'onwukachinonso06@gmail.com','display_name' => 'Samson'),
        //     array('user_email' => 'chukwuanidaberechi59@gmail.com','display_name' => 'Chukwuani Daberechi'),
        //     array('user_email' => 'annyuba176@gmai.com','display_name' => 'Uba Anny'),
        //     array('user_email' => 'Francis24724@gmail.com','display_name' => 'Martin'),
        //     array('user_email' => 'anabaraonyechiemelie@gmail.com','display_name' => 'Anabaraonye Chiemelie Raphael'),
        //     array('user_email' => 'Ultimatefashionworld440@gmil.com','display_name' => 'Segunbaba'),
        //     array('user_email' => 'adeyemimariam2018@gmail.com','display_name' => 'ADEYEMI101'),
        //     array('user_email' => 'exquisitepresley@gmail.com','display_name' => 'Exquisite Presley Brand'),
        //     array('user_email' => 'exquisitepresleybrand@gmail.com','display_name' => 'Exquisite Presley Graphics design brand'),
        //     array('user_email' => 'Uduakobongedet98@gmail.com','display_name' => 'YB Services'),
        //     array('user_email' => 'chinonsoonwuka06@gmail.com','display_name' => 'Chinonso Onwuka'),
        //     array('user_email' => 'adewaleahmed28@gmail.com','display_name' => 'Lasisi Adewale'),
        //     array('user_email' => 'Nkracheal327@gmail.com','display_name' => 'N. K stiches'),
        //     array('user_email' => 'ademolatemitope90@gmail.com','display_name' => 'KAREEM100'),
        //     array('user_email' => 'Treasureogbonnaya199@gmail.com','display_name' => 'Lovetha01'),
        //     array('user_email' => 'Okwuchukwuchibuike@gmail.com','display_name' => 'Chibyk'),
        //     array('user_email' => 'ayomiposioluyemi@gmail.com','display_name' => 'Kahunascion'),
        //     array('user_email' => 'samuelrichard877@gmail.com','display_name' => 'ADEYEMI100'),
        //     array('user_email' => 'ezekielafolabi22@gmail.com','display_name' => 'Ezekiel Afolabi'),
        //     array('user_email' => 'Demiladedfu24@gmail.com','display_name' => 'OLUWATOBILOBA100'),
        //     array('user_email' => 'edehmicheal416@gmail.com','display_name' => 'Micheal'),
        //     array('user_email' => 'envybees@gmail.com','display_name' => 'Onyeamar'),
        //     array('user_email' => 'bazeone4@gmail.com','display_name' => 'bazeone'),
        //     array('user_email' => 'greatmind465@gmail.com','display_name' => 'Greatmind'),
        //     array('user_email' => 'plateaumot@gmail.com','display_name' => 'olivergbenga1'),
        //     array('user_email' => 'toheeboyebola2@gmail.com','display_name' => 'Tee Cash Aluminium'),
        //     array('user_email' => 'evelyndfairgirl@gmail.com','display_name' => 'Evelyn'),
        //     array('user_email' => 'adesholaadebowale6@gmail.com','display_name' => 'Adeshola Adebowale'),
        //     array('user_email' => 'dupefemijohn@gmail.com','display_name' => 'Femi'),
        //     array('user_email' => 'emmanuelayinde111@gmail.com','display_name' => 'Rotel wrought iron'),
        //     array('user_email' => 'beatricetobi@gmail.com','display_name' => 'Beatrice'),
        //     array('user_email' => 'tolulope.daramola.id@gmail.com','display_name' => 'Adeleke Tolulope'),
        //     array('user_email' => 'cqualitycreations@gmail.com','display_name' => 'Quality Creation'),
        //     array('user_email' => 'Kachibofficial@gmail.com','display_name' => 'Kachibuzor'),
        //     array('user_email' => 'ajibolababatunde25@gmail.com','display_name' => 'Tunnero'),
        //     array('user_email' => 'emmanuelimade1@gmail.com','display_name' => 'Eminent01'),
        //     array('user_email' => 'ceoyem001@gmail.com','display_name' => 'Moses Leke'),
        //     array('user_email' => 'jollysmart@24gmail.com','display_name' => 'Mowhrode Dennis smart'),
        //     array('user_email' => 'blessingfausty83@gmail.com','display_name' => 'MDigital studio'),
        //     array('user_email' => 'idahosaclinton9@gmail.com','display_name' => '2Bcomputers'),
        //     array('user_email' => 'nkemmolokwu234@gmail.com','display_name' => 'Tailored by Nkay'),
        //     array('user_email' => 'oghiemiracle@gmail.com','display_name' => 'BeadsByMO'),
        //     array('user_email' => 'asonyejoy@gmail.com','display_name' => 'Choice collection'),
        //     array('user_email' => 'darosbeautyhome@gmail.com','display_name' => 'Ighodaro Osarenmwinda'),
        //     array('user_email' => 'Beautybridalconsultant@gmail.co','display_name' => 'Beautybridal_consultant'),
        //     array('user_email' => 'Titilayolightnoble@gmail.com','display_name' => 'TILA\'S LAUNDRY AND CLEANING SERVICE'),
        //     array('user_email' => 'micropreneuraugusta@gmail.com','display_name' => 'Ag Essentials'),
        //     array('user_email' => 'chinonsosuccess56@gmail.com','display_name' => 'Success Chinonso'),
        //     array('user_email' => 'osunderich@gmail.com','display_name' => 'Eno_Empire'),
        //     array('user_email' => 'omahkeni21@gmail.com','display_name' => 'AVID PAINTS'),
        //     array('user_email' => 'alekeangela38@gmail.com','display_name' => 'Angela Aleke'),
        //     array('user_email' => 'davidsonnorman79@gmail.com','display_name' => 'Mattok'),
        //     array('user_email' => 'graceobanor8@gmail.com','display_name' => 'Obanor Grace'),
        //     array('user_email' => 'stephensruthy1794@gmail.com','display_name' => 'Xterra')
        //   );


        foreach ($users as $userData) {
            $user = User::create([
                'name' => $userData['name'],
                'email' => $userData['email'],
                'password' => Hash::make('Password123'),
                'role_id' => 2,
            ]);

            // Send email notification
            // Mail::to($user->email)->send(new MigrationNotification($user));
            Mail::to($user->email)->send(new UpdateProfileMail($userData['name'], $userData['email'], 'Password123'));
        }
    }
}
